version: "3.6"
services:
  # Orion is the context broker
  orion:
    image: fiware/orion:2.4.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    ports:
      - "1026:1026" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  quantumleap:
    image: smartsdk/quantumleap
    hostname: quantumleap
    container_name: fiware-quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
      - orion
    environment:
      - CRATE_HOST=192.168.1.28
      - QL_DB_PASS=*
      - QL_DB_INIT_DIR=/ql-db-init
      - LOGLEVEL=DEBUG
      - QL_CORS_ALLOWED_ORIGIN=__ALL

  # Databases
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" # localhost:27017 # localhost:27017
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data

  crate-db:
    image: crate:3.1.2
    hostname: crate-db
    container_name: db-crate
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: crate -Clicense.enterprise=false -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - crate-db:/data

  reverse:
    image: nicolasferry/reverse
    hostname: reverse
    container_name: reverse
    ports:
      - "80:80"
    depends_on:
      - quantumleap

volumes:
  mongo-db: ~
  crate-db: ~

