version: "3.6"
services:

  # Database
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" # localhost:27017 # localhost:27017
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data

  serveur:
    image: nginx:alpine
    hostname: server
    container_name: server
    ports:
      - "80:80"


